### ISSUE TITLE
Demo page lacks example URL, SSL-off option

### ISSUE THREAD

**Issue by echo-bravo-yahoo** [dxc-technology/dxc-halstack-browser#1]
Hey! I'm looking into dxc-halstack-browser and tried the [demo page](https://hal.us.insurance.dxc.com/), but there's no example HAL API pre-filled in the link. I don't currently have a live HAL API, so I'd like to use a public / open HAL API. While looking around, I found a public HAL API at [this URL](http://api.opensupporter.org/api/v1), but it has an invalid SSL certificate.

Using the demo against an invalid SSL cert by visiting [https://api.opensupporter...](https://api.opensupporter.org/api/v1) gives the error `xhr.js:155 OPTIONS https://api.opensupporter.org/api/v1 net::ERR_CERT_COMMON_NAME_INVALID`. Attempting to request the resource /v1 over HTTP results in the error `xhr.js:155 Mixed Content: The page at 'https://hal.us.insurance.dxc.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.opensupporter.org/api/v1'. This request has been blocked; the content must be served over HTTPS.`. Attempting to downgrade the demo page to HTTP automatically redirects to HTTPS.

**Comment by peibolsang** [comment]
Hello, I have re-configured CF distribution for demo page so it does not redirect to HTTPS automatically. You should be able to access the demo page using HTTP also.

With regards to a valid hypermedia API, I reckon they are hard to find in the wild. Especially if you find some like the one above, it is important that they really are hypermedia and auto-discoverable, implementing the HATEOAS pattern. This is, they should be HTTP-OPTIONS-based. This means that you don't interact with the APIs directly using HTTP GET, but you first trigger an HTTP OPTIONS to discover what interactions and properties are possible with that API. This is one of the foundational concepts of Halstack Browser.

This type of APIs are becoming popular for enteprise systems, but again, I reckon they are difficult to find in the wild.

**Comment by echo-bravo-yahoo** [comment]
Ok! This fixes the issue I was having; closing the issue. Thanks :)
